name = "Dga"
uuid = "485024a0-7f6f-11e9-3e0c-f3dc302c285c"
authors = ["cckuailong"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
